### ISSUE TITLE
Beta Release & Production Deploy Checklist

### ISSUE THREAD

**Issue by NagariaHussain** [fossunited/printrov_merch_store#10]
To be done in Season Finale: [Building an Online Merchandise Store for FOSS United, Part 10](https://www.youtube.com/live/3jRGGH7f7tg?si=qmMEDmU3qpg08YYj)

### Beta Release

- [x] README / docs
- [x] Minor fixes:
    - [x] `any` perf
    - [x] Move Printrove Order details to Fulfilment tab
    - [x] Orders page navigation
- [x] Push tags and create GitHub release

### Deployment

- [x] New Instance on Frappe Cloud (Private Bench)
- [x] Setup Custom Domain (HackerMerch.store)
- [x] Setup Outgoing Emails
- [x] Configure Settings / Add Credentials
- [x] Create Invoice Print Format with Print Designer
- [x] Setup Home Page
